//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TableStock
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TableStock()
        {
            this.TableDividends = new HashSet<TableDividends>();
            this.TablePortfolio = new HashSet<TablePortfolio>();
        }

        [Required]
        [Display(Name = "Тикер")]
        public string ticker { get; set; }

        [Required]
        [Display(Name = "Сектор")]
        public Nullable<int> sectorId { get; set; }

        [Required]
        [Display(Name = "Отрасль")]
        public Nullable<int> departmentId { get; set; }

        [Required]
        [Display(Name = "Название")]
        public string name { get; set; }

        [Required]
        [Display(Name = "Размер лота")]
        public int lot { get; set; }

        [Required]
        [Display(Name = "Валюта")]
        public string currencyCode { get; set; }

        [Required]
        [Display(Name = "Биржа")]
        public string exchangeCode { get; set; }

        [Display(Name = "Примечание")]
        public string note { get; set; }

        [Display(Name = "P/E")]
        public Nullable<decimal> pe { get; set; }

        [Display(Name = "P/S")]
        public Nullable<decimal> ps { get; set; }

        [Display(Name = "Debt/Eq")]
        public Nullable<decimal> debtEq { get; set; }

        [Display(Name = "Цена")]
        public Nullable<decimal> price { get; set; }

        [Display(Name = "Мин.цена")]
        public Nullable<decimal> priceW52High { get; set; }

        [Display(Name = "Макс.цена")]
        public Nullable<decimal> priceW52Low { get; set; }

        [Display(Name = "Валюта")]
        public virtual TableCurrency TableCurrency { get; set; }

        [Display(Name = "Отрасль")]
        public virtual TableDepartment TableDepartment { get; set; }
        
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TableDividends> TableDividends { get; set; }
        public virtual TableExchange TableExchange { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TablePortfolio> TablePortfolio { get; set; }
        public virtual TableSector TableSector { get; set; }
    }
}
