//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TablePortfolio
    {
        public int Id { get; set; }

        [Display(Name = "Пользователь")]
        public int userId { get; set; }

        [Display(Name = "Тикер")]
        public string ticker { get; set; }

        [Display(Name = "Кол-во")]
        public int count { get; set; }

        [Display(Name = "Дата покупки")]
        [DataType(DataType.Date)]
        public System.DateTime dateBue { get; set; }

        [Display(Name = "Цена покупки")]
        public decimal priceBue { get; set; }

        [Display(Name = "Дата продажи")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> dateSell { get; set; }

        [Display(Name = "Цена продажи")]
        public Nullable<decimal> priceSell { get; set; }

        [Display(Name = "Акция")]
        public virtual TableStock TableStock { get; set; }

        [Display(Name = "Пользователь")]
        public virtual TableUser TableUser { get; set; }
    }
}
