//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TableDividends
    {
        [Display(Name = "Тикер")]
        public string ticker { get; set; }

        [Display(Name = "Дата отсечки")]
        [DataType(DataType.Date)]
        public System.DateTime dateCutoff { get; set; }

        [Display(Name = "Дата закрытия реестра")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> dateRegisterClosing { get; set; }

        [Display(Name = "Дата выплаты")]
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> datePay { get; set; }

        [Display(Name = "Сумма на 1 акцию")]
        public Nullable<double> amount { get; set; }

        [Display(Name = "Доходность")]
        public Nullable<double> profitability { get; set; }

        [Display(Name = "Название")]
        public virtual TableStock TableStock { get; set; }
    }
}
